### ISSUE TITLE
生成的字体能否指定输出目录？

### ISSUE THREAD

**Issue by gqbre** [aui/gulp-font-spider#12]
RT.
文档里并没有找到，是否考虑添加此功能？

**Comment by aui** [comment]
考虑到没有提供此功能，不过你可以通过 gulp 或者 grunt 很方便的实现

**Comment by lancelot-lewis** [comment]
@aui 能不能给出gulp实现指定输出目录的方法，新手请见谅。

**Comment by aui** [comment]
将压缩后的文件用 gulp 再拷贝到其他目录

**Comment by gqbre** [comment]
@LancelotLewis  可以参考一下 http://www.sheyilin.cn/2016/07/gulp_fontspider/
