### ISSUE TITLE
npm报这个错如何解决

### ISSUE THREAD

**Issue by slj20** [aui/gulp-font-spider#18]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "font-spider" "-g"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 no such package available : @gulp-sourcemaps/map-sources
npm ERR! 404
npm ERR! 404  '@gulp-sourcemaps/map-sources' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'gulp-sourcemaps'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\git\gulp-font-spider\npm-debug.log

**Comment by aui** [comment]
可能是 npm 的故障，建议你重试。或者给 npm 提交 BUG

**Comment by slj20** [comment]
mac 里安装也报错
npm ERR! code E404
npm ERR! 404 Not Found: @gulp-sourcemaps/map-sources@1.X

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxxx/.npm/_logs/2018-02-09T08_23_26_097Z-debug.log

**Comment by slj20** [comment]
换成cnpm可以安装了
